### ISSUE TITLE
[Feature Request] Display the Range of a Tower When Planning

### ISSUE THREAD

**Issue by greenDarkness** [piepie62/Foresight#2]
Hey there, just wanted to suggest showing the range of the tower when placing a ghost tower would be very helpful. 
I know that different gems have different ranges; however, even the minimum range for lv1 gems would be very useful.
A more dynamic solution would be to make it so that the last gem clicked sets the range of the tower that is being planned. 
Please let me know what you think. Thanks!

**Comment by piepie62** [comment]
Just added it for G1 gems. I'll think on how best to make it work for other grades, and possibly nonstandard combinations

**Comment by piepie62** [comment]
Other grades now work through the pair of grade selection buttons in the inventory. I consider this done

**Comment by greenDarkness** [comment]
Perfect. Thanks so much!
